server:
  port: 8080

spring:
  application:
    name: scholarship-management
  jpa:
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
    username: 'postgres123'
    url: jdbc:postgresql://scholarship-management-system.cwp0yoamk39n.us-east-1.rds.amazonaws.com:5432/postgres

  mail:
    host: smtp.gmail.com
    username: group3sfwe@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: qfnmqsktnqdlemgm


tracing:
  url: http://localhost:4317

management:
 tracing:
  sampling:
    probability: 1.0

